# Generated by Django 5.2.10 on 2026-01-16 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        ("tenants", "0004_alter_tenant_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analyticsevent",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                    ("patient_view", "Patient View"),
                    ("patient_create", "Patient Create"),
                    ("patient_edit", "Patient Edit"),
                    ("appointment_create", "Appointment Create"),
                    ("appointment_edit", "Appointment Edit"),
                    ("appointment_cancel", "Appointment Cancel"),
                    ("clinical_record_create", "Clinical Record Create"),
                    ("clinical_record_view", "Clinical Record View"),
                    ("lab_result_create", "Lab Result Create"),
                    ("lab_result_view", "Lab Result View"),
                    ("document_upload", "Document Upload"),
                    ("referral_create", "Referral Create"),
                    ("payment_received", "Payment Received"),
                    ("report_generated", "Report Generated"),
                    ("other", "Other Event"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="metadata",
            field=models.JSONField(
                blank=True, help_text="Additional event data (JSON format)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_events",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="user_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["tenant", "event_type", "timestamp"],
                name="analytics_a_tenant__1b4d98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["tenant", "user_id", "timestamp"],
                name="analytics_a_tenant__94edd4_idx",
            ),
        ),
    ]
