# Generated by Django 4.2.27 on 2026-01-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical_records", "0002_clinicalrecord_note_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalrecord",
            name="allergy_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="assessment_diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="chief_complaint",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="history_of_present_illness",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="investigation_results",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="investigations_ordered",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="medications_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="past_medical_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="physical_exam_auscultation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="physical_exam_inspection",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="physical_exam_palpation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="physical_exam_percussion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="plan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="provisional_diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalrecord",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="clinicalrecord",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
