# Generated by Django 4.2.27 on 2026-01-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_alter_patient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("P", "Prefer not to say"),
                ],
                help_text="Patient's gender for medical records",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="picture",
            field=models.ImageField(
                blank=True,
                help_text="Patient's profile picture",
                null=True,
                upload_to="patient_pictures/",
            ),
        ),
    ]
