# Generated by Django 4.2.27 on 2026-01-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0002_alter_labresult_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labresult",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
